/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panchkula;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;

/**
 *
 * @author Aarzoo
 */
public class Firstframe extends javax.swing.JFrame {

   /**
     * Creates new form Firstframe
     */
    public Firstframe() {
        initComponents();
     
        binddata();
        
     
    }
void binddata()
    {
        try
        {
              myconnection obj=new myconnection();
        String q="select * from tbcategory";
        PreparedStatement pst=obj.db.prepareStatement(q);
        ResultSet rs;
        rs=pst.executeQuery();
        String k;
        
        int x=950,y=150,w=200,h=55;
        
       // final int ix=300,iy=60,iw=200,ih=45;
        while(rs.next())
        {
            if(Integer.parseInt(rs.getString("pid"))==0)
            {
               
                   
           final JButton b=new JButton(rs.getString("cname"));
            
            b.setBounds(x,y,w,h);
            b.setToolTipText(""+rs.getInt("id"));       
            b.setForeground(Color.white);
            b.setBackground(Color.black);
           
           
            
           add(b);
           l1.add(b);
           
          // x=x+70;
           y=y+55;
          
          
           b.addActionListener(new ActionListener() {
             
                        @Override
                        public void actionPerformed(ActionEvent e) {
                           // System.out.println(b.getText()+" "+b.getToolTipText());
                           try
                           {myconnection obj1=new myconnection();
                            String y="select * from tbcategory where pid=?";
                            PreparedStatement post=obj1.db.prepareStatement(y);
                            post.setInt(1,Integer.parseInt(b.getToolTipText()));
        ResultSet res;
        res=post.executeQuery();
        if(res.next()!=false)
                            {
                                    
                            secondframe obj=new secondframe(Integer.parseInt(b.getToolTipText()));
                            obj.setVisible(true); 
                            
                            }
                           else
        {
            framelocation obj2=new framelocation(Integer.parseInt(b.getToolTipText()));
            obj2.setVisible(true);
            }
                                  }
                           catch(SQLException e1)
                           {
                               System.out.println(e1.getMessage());
                           }
                                   
                            
                        }
                    });
            
       
            }
            
            
          
        }
       
           }
        
        catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        button1.setBackground(new java.awt.Color(19, 23, 33));
        button1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("VISIT BLOG SECTION");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(20, 80, 173, 50);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("PANCHKULA ON MY FINGERTIPS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 30, 750, 50);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel2.setText("~A TOUCH OF HEAVEN ON NH-7!~");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 70, 310, 40);

        l1.setBackground(new java.awt.Color(255, 255, 255));
        l1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aarzoo\\Documents\\pklimages\\iStock-using-iPad-21652636.jpg")); // NOI18N
        l1.setText("jLabel1");
        getContentPane().add(l1);
        l1.setBounds(-280, -10, 1360, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
frmuserlogin obj=new frmuserlogin();
obj.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Firstframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Firstframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Firstframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Firstframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Firstframe().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables
};
