/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panchkula;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;

/**
 *
 * @author Aarzoo
 */
public class frame3 extends javax.swing.JFrame {

   int k; /**
     * Creates new form frame3
     */
    public frame3(int id) {
        initComponents();
        k=id;
        getdata();
    }
void getdata()
{
     try
                             {
                                
                                String q="select * from tbcategory where pid=?";
                                myconnection obj=new myconnection();
                                PreparedStatement pst=obj.db.prepareStatement(q);
                                pst.setInt(1,k);
                                ResultSet rs;
                                rs=pst.executeQuery();
                                int ix=0,iy=0,iw=0,ih=0;
                                while(rs.next())
                                {
                                    final JButton bsub=new JButton(rs.getString("cname"));
                                    bsub.setBounds(ix+40,iy+40, iw+200, ih+40);
                                   bsub.setToolTipText(""+rs.getInt("id"));
                                    add(bsub);
                                    iy=iy+40;
                                
                                 bsub.addActionListener(new ActionListener() {
             
                        @Override
                        public void actionPerformed(ActionEvent e) {
                           // System.out.println(b.getText()+" "+b.getToolTipText());
                          framelocation obj4=new framelocation(Integer.parseInt(bsub.getToolTipText()));
                          obj4.setVisible(true);
                            
                        }
                    });
            
                                }
                            }
                            catch(SQLException e1)
                            {
                               System.out.println(e1.getMessage()); 
                            }
                            
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new frame3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
