/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panchkula;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aarzoo
 */
public class framelocation extends javax.swing.JFrame {

    int k;/**
     * Creates new form framelocation
     */
    public framelocation(int id) {
        k=id;
        initComponents();
        display();
    }
    void display()
    {
        try{
            myconnection obj=new  myconnection();
            //Statement st;
            //st=(Statement) obj.db.createStatement();
             
            ResultSet rs;
            String q="Select * from tbdetails where categoryid=?";
            PreparedStatement pmst=obj.db.prepareStatement(q);
        pmst.setInt(1,k);
            //st.setInt(1,k);
            rs=pmst.executeQuery();
            String s[]=new String[]{"Name","Contact","Sector","Email","Location","Pincode"};
            DefaultTableModel dtm=new DefaultTableModel(s,0);
            int i=0;
           // int id;
            String a,b,c,d,e,f;
            while(rs.next())
            {
                a=rs.getString("name");
                b=rs.getString("contact");
                c=rs.getString("sector");
                d=rs.getString("email");
                e=rs.getString("location");
                f=rs.getString("pincode");
                dtm.addRow(new Vector());
                dtm.setValueAt(a, i, 0);
                dtm.setValueAt(b, i, 1);
                dtm.setValueAt(c, i, 2);
                dtm.setValueAt(d, i, 3);
  dtm.setValueAt(e, i, 4);
  dtm.setValueAt(f, i, 5);
  
                i++;
            }
            jt.setModel(dtm);
            
        }   
        catch(SQLException e )
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(880, 550));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(240, 209, 155));

        jt.setBackground(new java.awt.Color(65, 35, 21));
        jt.setForeground(new java.awt.Color(255, 255, 204));
        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt.setFillsViewportHeight(true);
        jt.setGridColor(new java.awt.Color(0, 0, 0));
        jt.setRowHeight(18);
        jt.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 860, 402);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aarzoo\\Documents\\pklimages\\writing-content-notes-ss-1920.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -6, 880, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framelocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framelocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framelocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framelocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
              //  new framelocation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt;
    // End of variables declaration//GEN-END:variables
}
